name: twitter trends
on: push # Every hour. Ref https://crontab.guru/examples.html

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get twitter data
      run: |
        pip3 install install pandas
        python3 twitter_trends.py
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you